export interface Chapter {
  id: string;
  country: string;
  theater: string;
  line: string;
  beats: [string, string, string];
  water: "river" | "coast" | "lakes";
  waterAmt: number;
  forest: number;
  peaks: number;
  salt: number;
  sky: [string, string];
  ground: [number, number, number];
  canopy: string;
  trunk: string;
  waterFill: string;
  snow: boolean;
}

export const CHAPTERS: Chapter[] = [
  {
    id: "usa",
    country: "United States",
    theater: "Cascade Reach",
    line: "Snow, cedar, and a ford the tanks have to take.",
    beats: [
      "Helion drops west of the Cascade. Ionite sits under the snow, and the river is the first wall.",
      "The column takes the ford. Infantry clears the cedar. Keep the pad behind the tree line.",
      "Vesper holds the far peak. Crack their spire before the air finds your glass.",
    ],
    water: "river",
    waterAmt: 0.7,
    forest: 0.62,
    peaks: 0.7,
    salt: 2.1,
    sky: ["#1c3348", "#8aa4b4"],
    ground: [92, 108, 78],
    canopy: "#2f5a3a",
    trunk: "#4a3424",
    waterFill: "#1a5870",
    snow: true,
  },
  {
    id: "russia",
    country: "Russia",
    theater: "White Meridian",
    line: "A frozen cut, birch, and a ridge that does not forgive.",
    beats: [
      "White Meridian. The river is a sheet of ice and the birch is thin cover.",
      "Move the tanks on the hard ground. Men die in the open between the trees.",
      "Their spire is on the high rock. End it before the cold takes the grid.",
    ],
    water: "river",
    waterAmt: 0.55,
    forest: 0.42,
    peaks: 0.9,
    salt: 5.4,
    sky: ["#243246", "#c5d0d8"],
    ground: [150, 156, 150],
    canopy: "#6d7c68",
    trunk: "#5c4030",
    waterFill: "#8ea8b8",
    snow: true,
  },
  {
    id: "australia",
    country: "Australia",
    theater: "Red Interior",
    line: "Red dirt, a dry creek, and mesas instead of a forest.",
    beats: [
      "Red Interior. The creek is low and the ionite glows in the scrub.",
      "There is little shade. Use the mesas. Do not line the tanks on open dirt.",
      "Vesper dug the spire into the far mesa. Break it and the horizon is yours.",
    ],
    water: "lakes",
    waterAmt: 0.35,
    forest: 0.28,
    peaks: 0.45,
    salt: 8.2,
    sky: ["#3a2418", "#e0a070"],
    ground: [168, 96, 58],
    canopy: "#6a7a38",
    trunk: "#6a4030",
    waterFill: "#2a6a78",
    snow: false,
  },
  {
    id: "korea",
    country: "South Korea",
    theater: "Han Line",
    line: "A wide river, dense cover, and a ridge on the far bank.",
    beats: [
      "The Han Line is a wet cut. Helion holds the near bank. The glass is across the water.",
      "Cross at the fords. Infantry owns the trees. Tanks own the open shelf.",
      "Their spire watches the far ridge. Silence it.",
    ],
    water: "river",
    waterAmt: 0.85,
    forest: 0.7,
    peaks: 0.55,
    salt: 3.3,
    sky: ["#163044", "#7ea0b0"],
    ground: [78, 108, 72],
    canopy: "#1f6a3c",
    trunk: "#3e2a1c",
    waterFill: "#186080",
    snow: false,
  },
  {
    id: "china",
    country: "China",
    theater: "Pearl Shelf",
    line: "Delta water, terrace rock, and a long approach.",
    beats: [
      "Pearl Shelf. The delta splits the ground into fingers. Ionite sits on the dry ones.",
      "Do not fight in the water. Hold the terraces and build the bay before they bomb the pad.",
      "The spire is inland. A straight push dies. Take the shelf, then the glass.",
    ],
    water: "lakes",
    waterAmt: 0.8,
    forest: 0.4,
    peaks: 0.35,
    salt: 6.6,
    sky: ["#1a3040", "#9eb8a8"],
    ground: [110, 120, 78],
    canopy: "#3d7a40",
    trunk: "#4a3428",
    waterFill: "#1c6878",
    snow: false,
  },
  {
    id: "japan",
    country: "Japan",
    theater: "Inland Sea",
    line: "Coast, cedar, and a volcanic ridge.",
    beats: [
      "Inland Sea. Helion lands on the coast. The water is at your back and the ridge is ahead.",
      "Cedar hides the infantry. The air comes in low over the water. Keep a lance up.",
      "Vesper's spire sits in the volcanic rock. Crack it and the chapter closes.",
    ],
    water: "coast",
    waterAmt: 0.75,
    forest: 0.66,
    peaks: 0.8,
    salt: 4.4,
    sky: ["#1a2838", "#d0a0a8"],
    ground: [86, 104, 70],
    canopy: "#245c34",
    trunk: "#3a2818",
    waterFill: "#14586e",
    snow: false,
  },
  {
    id: "uk",
    country: "United Kingdom",
    theater: "North Glass",
    line: "Grey water, low moor, and a short horizon.",
    beats: [
      "North Glass. Low cloud, a grey cut of water, and ionite in the moor.",
      "The ground is open. Walls matter more here than trees. Build the lane before you push.",
      "Their spire is not high. It is close. Finish it before the weather closes the air.",
    ],
    water: "coast",
    waterAmt: 0.5,
    forest: 0.3,
    peaks: 0.25,
    salt: 1.2,
    sky: ["#2a3340", "#9aa6b0"],
    ground: [96, 108, 78],
    canopy: "#3e6244",
    trunk: "#3c3024",
    waterFill: "#3a5a68",
    snow: false,
  },
  {
    id: "india",
    country: "India",
    theater: "Deccan Shelf",
    line: "A monsoon river, hard plateau, and a long gun line.",
    beats: [
      "Deccan Shelf. The river is up. The plateau is the only clean ground for a base.",
      "Infantry takes the scrub. Tanks stay on the shelf. Do not chase into the flood.",
      "The spire is beyond the last rise. Hold the lane, then break it.",
    ],
    water: "river",
    waterAmt: 0.8,
    forest: 0.48,
    peaks: 0.4,
    salt: 7.7,
    sky: ["#243028", "#e0c080"],
    ground: [140, 120, 64],
    canopy: "#4a7a32",
    trunk: "#5a3c24",
    waterFill: "#1a7068",
    snow: false,
  },
  {
    id: "france",
    country: "France",
    theater: "Atlantic Cut",
    line: "An estuary, hedgerows, and a stone ridge.",
    beats: [
      "Atlantic Cut. The estuary floods the low ground. Helion builds on the hedgerow shelf.",
      "Use the trees as walls. A tank in the open is a gift to their guns.",
      "Vesper's spire crowns the stone. Take the cut, then the glass.",
    ],
    water: "river",
    waterAmt: 0.6,
    forest: 0.55,
    peaks: 0.5,
    salt: 9.1,
    sky: ["#1e3044", "#b7c4c8"],
    ground: [100, 112, 70],
    canopy: "#2f6840",
    trunk: "#3e2c1e",
    waterFill: "#1a6074",
    snow: false,
  },
  {
    id: "brazil",
    country: "Brazil",
    theater: "Green Margin",
    line: "Heavy canopy, a dark river, and almost no open ground.",
    beats: [
      "Green Margin. The canopy hides both sides. The river is the only clean line on the map.",
      "Cut a lane before you mass tanks. Infantry can live in the trees. Vehicles cannot.",
      "The spire is a scar in the green. Find it, then burn the approach.",
    ],
    water: "river",
    waterAmt: 0.9,
    forest: 0.86,
    peaks: 0.3,
    salt: 10.5,
    sky: ["#102018", "#6a9870"],
    ground: [62, 92, 48],
    canopy: "#145028",
    trunk: "#2e2014",
    waterFill: "#0e5048",
    snow: false,
  },
];

export function chapterById(id: string | undefined): Chapter {
  return CHAPTERS.find((c) => c.id === id) ?? CHAPTERS[0];
}
